name = "spotify-mcp-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "MCP_OBJECT", class_name = "McpAgent" },
  { name = "SPOTIFY_SESSION", class_name = "SpotifySession" }
]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["McpAgent", "SpotifySession"]

[env.production]
name = "spotify-mcp-worker" 