name = "math-mcp-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "MCP_OBJECT", class_name = "McpAgent" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["McpAgent"]

[env.production]
name = "math-mcp-worker" 